from typing import Protocol
from uuid import UUID

from app.application.schemas import LaunchCallRequest

class WorkflowRepository(Protocol):
    async def list_for_tenant(self, tenant_id: str): ...
    async def create(self, tenant_id: str, data): ...
    async def get_for_tenant(self, tenant_id: str, workflow_id: UUID): ...

class CallRepository(Protocol):
    async def create_queued(self, tenant_id: str, workflow_id: UUID, request: LaunchCallRequest): ...
    async def mark_started(self, call_id: UUID, provider_call_id: str): ...

class VoiceProvider(Protocol):
    async def start_call(self, phone_number: str, assistant_id: str, metadata: dict) -> str: ...

class AutomationProvider(Protocol):
    async def trigger_workflow(self, webhook_url: str, payload: dict) -> None: ...
